# Generated by Django 5.1.1 on 2024-09-21 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_mae', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cidade_natal', models.CharField(max_length=255)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('doencas_preexistentes', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('fumante', models.BooleanField(default=False)),
                ('tipo_fumante', models.CharField(blank=True, max_length=255, null=True)),
                ('etilista', models.BooleanField(default=False)),
                ('uso_drogas_ilicitas', models.BooleanField(default=False)),
                ('cirurgias_realizadas', models.TextField(blank=True, null=True)),
                ('carteira_vacinacao', models.TextField(blank=True, null=True)),
                ('medicacoes_em_uso', models.TextField(blank=True, null=True)),
                ('uso_anticoncepcional', models.BooleanField(default=False)),
                ('qualidade_sono', models.CharField(blank=True, max_length=255, null=True)),
                ('ja_foi_gestante', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField()),
                ('observacoes_paciente', models.TextField(blank=True, null=True)),
                ('tipo_consulta', models.CharField(choices=[('Particular', 'Particular'), ('Convenio', 'Convênio'), ('SUS', 'SUS')], max_length=50)),
                ('primeira_consulta', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade_medico', models.CharField(max_length=255)),
                ('especialidade_consulta', models.CharField(max_length=255)),
                ('anamnese', models.TextField()),
                ('resultado_exames', models.TextField(blank=True, null=True)),
                ('evolucao_grafica', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
    ]
